### ISSUE TITLE
err=INVALIDCODE when logging with Discord Oauth2

### ISSUE THREAD

**Issue by ManucrackYT** [Qwaekactyl/Qwaekactyl#12]
![imagen](https://user-images.githubusercontent.com/71397795/232308293-3ddfca07-575f-47b0-9877-1840f1866da3.png)
I clicked continue logging button on discord oauth and it redirected me to login page again

**Comment by ManucrackYT** [comment]
Now i saw it was a secret problem so i reset secret key but now it shows this when clicking "Continue" button on Oauth2:

(node:15) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/container/api/oauth2.js:346:37
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ItzCrazyKns** [comment]
Thank you for reporting this issue. Based on the error message you provided, it appears that there is an issue with parsing JSON data returned from the panel. To further investigate this issue, I suggest logging the response coming from the panel and checking the API key to ensure it is correctly configured. You can add logging statements to the code that is handling the response from the panel to print out the response and inspect it for any errors. Make sure that your API key is correct with all read and write permissions.
