### ISSUE TITLE
Issue with DiscordAuth or oauth2

### ISSUE THREAD

**Issue by Dev-Span** [Qwaekactyl/Qwaekactyl#13]
If i try t login, its sending me an Error.

![Screenshot 2023-04-24 202210](https://user-images.githubusercontent.com/67538314/234083123-677151a6-2d51-4805-a7ad-527e5e0a7db9.png)

Btw. Can someone please make the settings file more easy to understand. It took me like 10 or 15 Minutes to understand it.

**Comment by Dev-Span** [comment]
Sry, it was my Fault. I forget to type in the domain.

**Comment by ItzCrazyKns** [comment]
The fix has already been told in #12
